### ISSUE TITLE
Can't load orderbook on Umbrel 1.3

### ISSUE THREAD

**Issue by pedromtcosta** [joinmarket-webui/jam#880]
I am seeing the following error message when opening the orderbook on JAM:
![Image](https://github.com/user-attachments/assets/57e97ea5-eb13-432e-8844-0c7fa21f758c)

inspecting the console I see the following error:
```
POST http://{MY UMBREL IP}:5002/obwatch/refreshorderbook 502 (Bad Gateway)
```

Can someone please help me on how to fix this? I am on JAM v0.3.0

**Comment by theborakompanioni** [comment]
Hey @86codyharris!

Restarting often helps. It might be related to https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1760.
Let's see if this is (also) fixed with the new release.

**Comment by 18c83fd3-25ea-4ed9-8205-2abeff9b3883** [comment]
Looking at the problem, I agree it appears to be the directory nodes JoinMarket is trying to connect to are outdated or offline. I pulled their latest joinmarket.cfg and loaded it but the logs still show only connecting every once in awhile. Order book stays busted unless you catch it just right. 

Do we know when they will be updated or added to? Should we add a error code to the order book if it is going to be awhile?

**Comment by theborakompanioni** [comment]
> Looking at the problem, I agree it appears to be the directory nodes JoinMarket is trying to connect to are outdated or offline. I pulled their latest joinmarket.cfg and loaded it but the logs still show only connecting every once in awhile. Order book stays busted unless you catch it just right.

Jam docker container will ship with an adapted version of the default config: https://github.com/joinmarket-webui/jam-docker/pull/148#issue-2923150225
Other than that, it is a configuration issue.

> Do we know when they will be updated or added to? 

No.

> Should we add a error code to the order book if it is going to be awhile?

Jam - being just a frontend for JM - cannot know as this data is not accessible via the API.

**Comment by 18c83fd3-25ea-4ed9-8205-2abeff9b3883** [comment]
Understood. Just looking for something else to work on.

**Comment by theborakompanioni** [comment]
> > Hey [@86codyharris](https://github.com/86codyharris)!
> > Restarting often helps. It might be related to [JoinMarket-Org/joinmarket-clientserver#1760](https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1760). Let's see if this is (also) fixed with a new release.
> 
> When is the new release expected?

Jam v0.4.0 is out. 🚀 

@pedromtcosta Please reopen if you still experience issues 🙏
